// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xedaqlkmfsjphnxlzxnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZGFxbGttZnNqcGhueGx6eG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjY5NjcsImV4cCI6MjA3MDM0Mjk2N30.DBsdvAWnRnmkv0yk90aOvlFgDf3X-Mdo5rHdc3O745M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});